Repository vaticle/typedb-ml, pull requests merged in 2019-12, with the labels that each got.

#106 Revise KGCN READMEs
  kglib/kgcn/.images/learning.png
  kglib/kgcn/.images/queried_subgraph.png
  kglib/kgcn/README.md
  kglib/kgcn/examples/diagnosis/README.md
  kglib/kgcn/examples/diagnosis/diagnosis.py
  kglib/kgcn/examples/diagnosis/images/diagnosis_schema.png
  kglib/kgcn/examples/diagnosis/images/graph_snippet.png
  kglib/kgcn/examples/diagnosis/images/learning.png
  kglib/kgcn/examples/diagnosis/images/queried_subgraph.png
  kglib/kgcn/images/edge_update.png
  kglib/kgcn/images/knowledge_graph_machine_learning.png
  kglib/kgcn/images/learning_pipeline.png
  kglib/kgcn/images/learning_pipeline.svg
  kglib/kgcn/images/message_passing.png
  kglib/kgcn/images/node_update.png
  kglib/kgcn/images/subgraph.png
  kglib/kgcn/images/subgraph.svg
  kglib/kgcn/images/subgraph_with_predictions.png
  kglib/kgcn/images/subgraph_with_predictions.svg
  kglib/kgcn/models/attribute.py
Labels: feature

#108 Don't Plot Preexisting Graph Elements
  kglib/kgcn/examples/diagnosis/.images/diagnosis_schema.png
  kglib/kgcn/examples/diagnosis/.images/graph_snippet.png
  kglib/kgcn/examples/diagnosis/.images/learning.png
  kglib/kgcn/examples/diagnosis/.images/queried_subgraph.png
  kglib/kgcn/examples/diagnosis/README.md
  kglib/kgcn/examples/diagnosis/images/graph_snippet.png
  kglib/kgcn/examples/diagnosis/images/learning.png
  kglib/kgcn/plot/plotting.py
  kglib/kgcn/plot/plotting_test.py
Labels: feature

#109 Refactor Graph Encoding
  kglib/kgcn/examples/diagnosis/diagnosis.py
  kglib/kgcn/pipeline/encode.py
  kglib/kgcn/pipeline/encode_test.py
  kglib/kgcn/pipeline/pipeline.py
Labels: refactor

#110 Refactor Attribute Embedder Construction
  .gitignore
  kglib/kgcn/learn/learn_IT.py
  kglib/kgcn/models/BUILD
  kglib/kgcn/models/core.py
  kglib/kgcn/models/core_IT.py
  kglib/kgcn/models/embedding.py
  kglib/kgcn/models/embedding_IT.py
  kglib/kgcn/models/embedding_test.py
  kglib/kgcn/pipeline/pipeline.py
Labels: refactor

#111 Fix test-deployment-pip CI job
  .circleci/config.yml
Labels: bug, build

#112 Remove Global Block and Input Field of Graphs
  kglib/kgcn/examples/diagnosis/diagnosis.py
  kglib/kgcn/learn/learn_IT.py
  kglib/kgcn/models/core.py
  kglib/kgcn/pipeline/utils_test.py
Labels: refactor

#113 Update client-python dependency for pip distribution
  BUILD
  dependencies/graknlabs/dependencies.bzl
Labels: build

#114 Revise diagnosis example
  kglib/kgcn/.images/basic_schema.png
  kglib/kgcn/.images/basic_schema.svg
  kglib/kgcn/.images/edge_update.png
  kglib/kgcn/.images/edge_update.svg
  kglib/kgcn/.images/edge_update_process.png
  kglib/kgcn/.images/interaction_edge_update.png
  kglib/kgcn/.images/interaction_edge_update.svg
  kglib/kgcn/.images/interaction_node_update.png
  kglib/kgcn/.images/interaction_node_update.svg
  kglib/kgcn/.images/knowledge_graph_machine_learning.png
  kglib/kgcn/.images/learning_pipeline.png
  kglib/kgcn/.images/learning_pipeline.svg
  kglib/kgcn/.images/message_passing.png
  kglib/kgcn/.images/node_update.png
  kglib/kgcn/.images/node_update.svg
  kglib/kgcn/.images/node_update_process.png
  kglib/kgcn/.images/reasoning.png
  kglib/kgcn/.images/reasoning.svg
  kglib/kgcn/.images/subgraph.png
  kglib/kgcn/.images/subgraph.svg
  kglib/kgcn/.images/subgraph_with_predictions.png
  kglib/kgcn/.images/subgraph_with_predictions.svg
  kglib/kgcn/.images/ternary_diagnosis.png
  kglib/kgcn/.images/ternary_diagnosis.svg
  kglib/kgcn/README.md
  kglib/kgcn/examples/diagnosis/.images/diagnosis_schema.png
  kglib/kgcn/examples/diagnosis/.images/graph.png
  kglib/kgcn/examples/diagnosis/.images/graph_snippet.png
  kglib/kgcn/examples/diagnosis/.images/learning.png
  kglib/kgcn/examples/diagnosis/.images/queried_subgraph.png
  kglib/kgcn/examples/diagnosis/README.md
  kglib/kgcn/examples/diagnosis/diagnosis.py
  kglib/kgcn/images/message_passing.png
  kglib/utils/grakn/synthetic/examples/diagnosis/generate.py
  kglib/utils/grakn/synthetic/examples/diagnosis/schema.gql
Labels: feature

#115 Diagnosis Example Fixes
  kglib/kgcn/examples/diagnosis/diagnosis.py
  kglib/kgcn/examples/diagnosis/diagnosis_test.py
  kglib/utils/graph/thing/queries_to_graph_it.py
Labels: refactor

#118 Simplify QueryGraph interface
  kglib/kgcn/examples/diagnosis/BUILD
  kglib/kgcn/examples/diagnosis/diagnosis.py
  kglib/kgcn/examples/diagnosis/diagnosis_test.py
  kglib/utils/graph/query/query_graph.py
  kglib/utils/graph/query/query_graph_test.py
Labels: refactor

#119 Fix QueryGraph construction
  kglib/kgcn/examples/diagnosis/diagnosis.py
  tests/end_to_end/kgcn/diagnosis.py
Labels: bug

#121 Increase version to 0.2.1
  VERSION
  dependencies/graknlabs/dependencies.bzl
Labels: build
