Repository vaticle/typedb-ml, pull requests merged in 2019-08, with the labels that each got.

#81 Move non-Grakn Dependency
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  dependencies/python/BUILD
  dependencies/python/dependencies.bzl
Labels: bug

#82 Apche license: update 2018 -> 2019
  LICENSE.txt
  dependencies/graknlabs/dependencies.bzl
Labels: refactor

#74 Generate synthetic graphs
  BUILD
  kglib/BUILD
  kglib/synthetic_graphs/BUILD
  kglib/synthetic_graphs/diagnosis/main.py
  kglib/synthetic_graphs/diagnosis/schema.gql
  kglib/synthetic_graphs/generate/BUILD
  kglib/synthetic_graphs/generate/pmf.py
  kglib/synthetic_graphs/generate/pmf_test.py
  requirements.txt
Labels: feature

#83 Create CODEOWNERS
  .github/CODEOWNERS
Labels: build
