Repository vaticle/typedb-ml, pull requests merged in 2019-05, with the labels that each got.

#60 Fix broken path in Readme and fix graql syntax
  examples/kgcn/animal_trade/README.md
Labels: bug

#62 Add Multi-label Classifier
  kglib/kgcn/learn/classify.py
  kglib/kgcn/learn/metrics/report.py
  kglib/kgcn/learn/metrics/report_test.py
Labels: feature, in progress

#63 Input pipeline refactor
  kglib/BUILD
  kglib/kgcn/core/ingest/encode/schema_test.py
  kglib/kgcn/core/ingest/traverse/data/context/array.py
  kglib/kgcn/core/ingest/traverse/data/context/array_IT.py
  kglib/kgcn/core/ingest/traverse/data/context/array_test.py
  kglib/kgcn/core/ingest/traverse/data/context/builder.py
  kglib/kgcn/core/ingest/traverse/data/context/builder_IT.py
  kglib/kgcn/core/ingest/traverse/data/context/builder_mocks.py
  kglib/kgcn/core/ingest/traverse/data/context/builder_test.py
  kglib/kgcn/core/ingest/traverse/data/context/neighbour.py
  kglib/kgcn/core/ingest/traverse/data/context/neighbour_test.py
  kglib/kgcn/core/model.py
Labels: refactor

#64 Refactor Classifiers
  examples/kgcn/animal_trade/README.md
  examples/kgcn/animal_trade/main.py
  examples/kgcn/animal_trade/test/end_to_end_test.py
  kglib/kgcn/README.md
  kglib/kgcn/learn/classify.py
Labels: refactor
